server:
  port: 9999
  
spring:
  application:
    name: order
eureka:
  client:
    service-url:
      defaultZone:  http://eurekaserver1:8222/eureka
  instance:
    instance-id: ${spring.application.name}:${server.port}
env: dev  
